version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "caganseyrek"
  - package-ecosystem: "npm"
    directory: "/apps/web-client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "caganseyrek"
  - package-ecosystem: "maven"
    directory: "/apps/data-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "caganseyrek"
  - package-ecosystem: "maven"
    directory: "/apps/auth-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "caganseyrek"
