version: "3.8"

services:
  flight-coordinator-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/src/main/resources/application.yml
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - fc-network

  flight-coordinator-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      flight-coordinator-server:
        condition: service_healty
    networks:
      - fc-network

networks:
  fc-network:
    driver: bridge
