services:
  flight-coordinator-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - flight-coordinator-server

  flight-coordinator-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
