from enum import Enum


class AirportType(str, Enum):
    INTERNATIONAL = "International"
    REGIONAL = "Regional"
    DOMESTIC = "Domestic"


class CertificationStatus(str, Enum):
    CERTIFIED = "Certified"
    PENDING_APPROVAL = "Pending Approval"
    REVOKED = "Revoked"
    UNDER_REVIEW = "Under Review"
    EXPIRED = "Expired"


class Certifier(str, Enum):
    FAA = "Federal Aviation Administration of United States"
    EASA = "European Union Aviation Safety Agency"
    CAA_UK = "Civil Aviation Authority of United Kingdom"
    CAA_NZ = "Civil Aviation Authority of New Zealand"
    CAA_PK = "Pakistan Civil Aviation Authority"
    CAD_HK = "Civil Aviation Department of Hong Kong"
    CAA_PH = "Civil Aviation Authority of the Philippines"
    CAA_SG = "Civil Aviation Authority of Singapore"
    TRANSPORT_CANADA = "Transport Canada"
    DGCA_TR = "Directorate General of Civil Aviation of Turkey"
    DGCA_IN = "Directorate General of Civil Aviation of India"
    DGCA_ID = "Directorate General of Civil Aviation of Indonesia"
    DGCA_KW = "Directorate General of Civil Aviation of Kuwait"
    CAAC = "Civil Aviation Administration of China"
    CASA = "Civil Aviation Safety Authority of Australia"
    ICAO = "International Civil Aviation Organization"
    ANAC = "National Civil Aviation Agency of Brazil"
    GCAA = "General Civil Aviation Authority of United Arab Emirates"
    SACAA = "South African Civil Aviation Authority"
    IATA = "International Air Transport Association"
    FLIGHT_SAFETY = "FlightSafety International"
    ATRA = "Aviation Training & Research Academy"
    LAT = "Lufthansa Aviation Training"
    CAE = "CAE Inc."


class CrewMemberRole(str, Enum):
    CAPTAIN = "Captain"
    FIRST_OFFICER = "First Officer"
    SECOND_OFFICER = "Second Officer"
    RELIEF_CREW_MEMBER = "Relief Crew Member"
    PURSER = "Purser"
    CABIN_SUPERVISOR = "Cabin Supervisor"
    FLIGHT_ATTENDANT = "Flight Attendant"
    FLIGHT_MEDIC = "Flight Medic"


class CrewMemberStatus(str, Enum):
    ACTIVE = "Active"
    INACTIVE = "Inactive"
    ON_LEAVE = "On-Leave"
    RETIRED = "Retired"


class EngineType(str, Enum):
    TURBOJET = "Turbo Jet"
    TURBOPROP = "Turbo Propeller"
    TURBOFAN = "Turbo Fan"
    RAMJET = "Ram Jet"
    SCRAMJET = "Scram Jet"
    PISTON = "Piston"
    ELECTRIC = "Electric"
    HYBRID_ELECTRIC = "Hybric Electric"
    HYDROGEN_FUEL_CELL = "Hydrogen Fuel Cell"


class NoiseCategory(str, Enum):
    CHAPTER_2 = "Chapter 2 - Older, louder aircraft"
    CHAPTER_3 = "Chapter 3 - Modern aircraft with standard noise levels"
    CHAPTER_4 = "Chapter 4 - Latest generation, significantly quieter"
    CHAPTER_14 = "Chapter 14 - Most recent standard, strictest noise regulations"


class PlaneStatus(str, Enum):
    ACTIVE = "Active"
    UNDER_MAINTENANCE = "Under-Maintenance"
    INACTIVE = "Inactive"
    RETIRED = "Retired"


class RunwayStatus(str, Enum):
    OPEN = "Open"
    CLOSED = "Closed"
    MAINTENANCE = "Under Maintenance"
    UNDER_CONSTRUCTION = "Under Construction"
    EMERGENCY_USE_ONLY = "Emergency Use Only"


class SurfaceType(str, Enum):
    ASPHALT = "Asphalt"
    CONCRETE = "Concrete"
    GRASS = "Grass"
    GRAVEL = "Gravel"
    DIRT = "Dirt"
    COMP_MATERIAL = "Composite Materials"


class VisualApproachAid(str, Enum):
    PAPI = "Precision Approach Path Indicator"
    VASI = "Visual Approach Slope Indicator"
    ALSF1 = "Approach Lighting System with Sequenced Flashers I"
    ALSF2 = "Approach Lighting System with Sequenced Flashers II"
    ODALS = "Omni-Directional Approach Lighting System"
    MALSR = "Medium Intensity Approach Lighting System with Runway Alignment Indicator Lights"
    SSALR = "Simplified Short Approach Lighting System with Runway Alignment Indicator Lights"
    MALS = "Medium Intensity Approach Lighting System"
    REIL = "Runway End Identifier Lights"
    HIRL = "High Intensity Runway Lights"
    MIRL = "Medium Intensity Runway Lights"
    LIR = "Low Intensity Runway Lights"
    NONE = "None"


class CountryCode(str, Enum):
    US = "United States"
    AF = "Afghanistan"
    AX = "Aland Islands"
    AL = "Albania"
    DZ = "Algeria"
    AS = "American Samoa"
    AD = "Andorra"
    AO = "Angola"
    AI = "Anguilla"
    AQ = "Antarctica"
    AG = "Antigua And Barbuda"
    AR = "Argentina"
    AM = "Armenia"
    AW = "Aruba"
    AU = "Australia"
    AT = "Austria"
    AZ = "Azerbaijan"
    BS = "Bahamas"
    BH = "Bahrain"
    BD = "Bangladesh"
    BB = "Barbados"
    BY = "Belarus"
    BE = "Belgium"
    BZ = "Belize"
    BJ = "Benin"
    BM = "Bermuda"
    BT = "Bhutan"
    BO = "Bolivia"
    BQ = "Bonaire, Sint Eustatius, and Saba"
    BA = "Bosnia And Herzegovina"
    BW = "Botswana"
    BV = "Bouvet Island"
    BR = "Brazil"
    IO = "British Indian Ocean Territory"
    BN = "Brunei Darussalam"
    BG = "Bulgaria"
    BF = "Burkina Faso"
    BI = "Burundi"
    KH = "Cambodia"
    CM = "Cameroon"
    CA = "Canada"
    CV = "Cape Verde"
    KY = "Cayman Islands"
    CF = "Central African Republic"
    TD = "Chad"
    CL = "Chile"
    CN = "China"
    CX = "Christmas Island"
    CC = "Cocos (Keeling) Islands"
    CO = "Colombia"
    KM = "Comoros"
    CG = "Congo"
    CD = "Congo Democratic Republic"
    CK = "Cook Islands"
    CR = "Costa Rica"
    CI = "Cote D'Ivoire"
    HR = "Croatia"
    CU = "Cuba"
    CW = "Curaçao"
    CY = "Cyprus"
    CZ = "Czech Republic"
    DK = "Denmark"
    DJ = "Djibouti"
    DM = "Dominica"
    DO = "Dominican Republic"
    EC = "Ecuador"
    EG = "Egypt"
    SV = "El Salvador"
    GQ = "Equatorial Guinea"
    ER = "Eritrea"
    EE = "Estonia"
    ET = "Ethiopia"
    FK = "Falkland Islands"
    FO = "Faroe Islands"
    FJ = "Fiji"
    FI = "Finland"
    FR = "France"
    GF = "French Guiana"
    PF = "French Polynesia"
    TF = "French Southern Territories"
    GA = "Gabon"
    GM = "Gambia"
    GE = "Georgia"
    DE = "Germany"
    GH = "Ghana"
    GI = "Gibraltar"
    GR = "Greece"
    GL = "Greenland"
    GD = "Grenada"
    GP = "Guadeloupe"
    GU = "Guam"
    GT = "Guatemala"
    GG = "Guernsey"
    GN = "Guinea"
    GW = "Guinea Bissau"
    GY = "Guyana"
    HT = "Haiti"
    HM = "Heard Island and Mcdonald Islands"
    VA = "Vatican City State"
    HN = "Honduras"
    HK = "Hong Kong"
    HU = "Hungary"
    IS = "Iceland"
    IN = "India"
    ID = "Indonesia"
    IR = "Iran"
    IQ = "Iraq"
    IE = "Ireland"
    IM = "Isle Of Man"
    IL = "Israel"
    IT = "Italy"
    JM = "Jamaica"
    JP = "Japan"
    JE = "Jersey"
    JO = "Jordan"
    KZ = "Kazakhstan"
    KE = "Kenya"
    KI = "Kiribati"
    KR = "Republic of Korea"
    KP = "Democratic People's Republic of Korea"
    KW = "Kuwait"
    KG = "Kyrgyzstan"
    LA = "Lao People'ss Democratic Republic"
    LV = "Latvia"
    LB = "Lebanon"
    LS = "Lesotho"
    LR = "Liberia"
    LY = "Libya"
    LI = "Liechtenstein"
    LT = "Lithuania"
    LU = "Luxembourg"
    MO = "Macao"
    MK = "Macedonia"
    MG = "Madagascar"
    MW = "Malawi"
    MY = "Malaysia"
    MV = "Maldives"
    ML = "Mali"
    MT = "Malta"
    MH = "Marshall Islands"
    MQ = "Martinique"
    MR = "Mauritania"
    MU = "Mauritius"
    YT = "Mayotte"
    MX = "Mexico"
    FM = "Micronesia"
    MD = "Moldova"
    MC = "Monaco"
    MN = "Mongolia"
    ME = "Montenegro"
    MS = "Montserrat"
    MA = "Morocco"
    MZ = "Mozambique"
    MM = "Myanmar"
    NA = "Namibia"
    NR = "Nauru"
    NP = "Nepal"
    NL = "Netherlands"
    NC = "New Caledonia"
    NZ = "New Zealand"
    NI = "Nicaragua"
    NE = "Niger"
    NG = "Nigeria"
    NU = "Niue"
    NF = "Norfolk Island"
    MP = "Northern Mariana Islands"
    NO = "Norway"
    OM = "Oman"
    PK = "Pakistan"
    PW = "Palau"
    PS = "Palestinian Territory"
    PA = "Panama"
    PG = "Papua New Guinea"
    PY = "Paraguay"
    PE = "Peru"
    PH = "Philippines"
    PN = "Pitcairn"
    PL = "Poland"
    PT = "Portugal"
    PR = "PuertoRico"
    QA = "Qatar"
    RE = "Reunion"
    RO = "Romania"
    RU = "Russian Federation"
    RW = "Rwanda"
    BL = "Saint Barthelemy"
    SH = "Saint Helena"
    KN = "Saint Kitts And Nevis"
    LC = "SaintLucia"
    MF = "SaintMartin"
    PM = "Saint Pierre And Miquelon"
    VC = "Saint Vincent And the Grenadines"
    WS = "Samoa"
    SM = "San Marino"
    ST = "Sao Tome And Principe"
    SA = "Saudi Arabia"
    SN = "Senegal"
    RS = "Serbia"
    SC = "Seychelles"
    SL = "Sierra Leone"
    SG = "Singapore"
    SX = "Sint Maarten"
    SK = "Slovakia"
    SI = "Slovenia"
    SB = "Solomon Islands"
    SO = "Somalia"
    ZA = "South Africa"
    GS = "South Georgia and the South Sandwich Islands"
    SS = "South Sudan"
    ES = "Spain"
    LK = "Sri Lanka"
    SD = "Sudan"
    SR = "Suriname"
    SJ = "Svalbard And Jan Mayen"
    SZ = "Swaziland"
    SE = "Sweden"
    CH = "Switzerland"
    SY = "Syrian Arab Republic"
    TW = "Taiwan"
    TJ = "Tajikistan"
    TZ = "Tanzania"
    TH = "Thailand"
    TL = "Timor Leste"
    TG = "Togo"
    TK = "Tokelau"
    TO = "Tonga"
    TT = "Trinidad And Tobago"
    TN = "Tunisia"
    TR = "Turkey"
    TM = "Turkmenistan"
    TC = "Turks And Caicos Islands"
    TV = "Tuvalu"
    UG = "Uganda"
    UA = "Ukraine"
    AE = "United Arab Emirates"
    GB = "United Kingdom"
    UM = "United States Outlying Islands"
    UY = "Uruguay"
    UZ = "Uzbekistan"
    VU = "Vanuatu"
    VE = "Venezuela"
    VN = "VietNam"
    VG = "British Virgin Islands"
    VI = "US Virgin Islands"
    WF = "Wallis And Futuna"
    EH = "Western Sahara"
    YE = "Yemen"
    ZM = "Zambia"
    ZW = "Zimbabwe"
