spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flightc_db
    username: local
    password: local
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 8081

api:
  version: v1
