const labelValueArrays = {
  AirportType: [
    { label: "International", value: "INTERNATIONAL" },
    { label: "Regional", value: "REGIONAL" },
    { label: "Domestic", value: "DOMESTIC" },
  ],
  CertificationIssuer: [
    { label: "Federal Aviation Administration", value: "FAA" },
    { label: "European Union Aviation Safety Agency", value: "EASA" },
    { label: "Civil Aviation Authority", value: "CAA" },
    { label: "Transport Canada", value: "TRANSPORT_CANADA" },
    { label: "Directorate General of Civil Aviation", value: "DGCA" },
    { label: "Civil Aviation Administration of China", value: "CAAC" },
    { label: "Civil Aviation Safety Authority", value: "CASA" },
    { label: "International Civil Aviation Organization", value: "ICAO" },
    { label: "Agência Nacional de Aviação Civil", value: "ANAC" },
    { label: "General Civil Aviation Authority", value: "GCAA" },
    { label: "South African Civil Aviation Authority", value: "SACAA" },
    { label: "Boeing", value: "BOEING" },
    { label: "Airbus", value: "AIRBUS" },
    { label: "Cessna", value: "CESSNA" },
    { label: "Embraer", value: "EMBRAER" },
    { label: "Bombardier", value: "BOMBARDIER" },
    { label: "Dassault Aviation", value: "DASSAULT" },
    { label: "Gulfstream", value: "GULFSTREAM" },
    { label: "International Air Transport Association", value: "IATA" },
    { label: "Red Cross", value: "RED_CROSS" },
    { label: "American Heart Association", value: "AHA" },
    { label: "FlightSafety International", value: "FLIGHT_SAFETY" },
    { label: "CAE", value: "CAE" },
  ],
  CertificationIssuingCountry: [
    { label: "United States", value: "US" },
    { label: "European Union", value: "EU" },
    { label: "Canada", value: "CANADA" },
    { label: "India", value: "INDIA" },
    { label: "China", value: "CHINA" },
    { label: "Australia", value: "AUSTRALIA" },
    { label: "United Arab Emirates", value: "UAE" },
    { label: "Global", value: "GLOBAL" },
  ],
  CrewAvailability: [
    { label: "Available", value: "AVAILABLE" },
    { label: "On-Duty", value: "ON_DUTY" },
    { label: "On-Leave", value: "ON_LEAVE" },
    { label: "Unavailable", value: "UNAVAILABLE" },
  ],
  CrewRole: [
    { label: "Captain", value: "CAPTAIN" },
    { label: "First Officer", value: "FIRST_OFFICER" },
    { label: "Seconds Officer", value: "SECOND_OFFICER" },
    { label: "Third Officer", value: "THIRD_OFFICER" },
    { label: "Relief Crew Member", value: "RELIEF_CREW_MEMBER" },
    { label: "Flight Engineer", value: "FLIGHT_ENGINEER" },
    { label: "Airborne Sensor Opr.", value: "AIRBORNE_SENSOR_OPR" },
    { label: "Purser", value: "PURSER" },
    { label: "Flight Attendant", value: "FLIGHT_ATTENDANT" },
    { label: "Flight Medic", value: "FLIGHT_MEDIC" },
    { label: "Loadmaster", value: "LOADMASTER" },
  ],
  PlaneAvailability: [
    { label: "Available", value: "AVAILABLE" },
    { label: "Under-Maintenance", value: "UNDER_MAINTENANCE" },
    { label: "In-Use", value: "IN_USE" },
    { label: "Retired", value: "RETIRED" },
  ],
  RunwaySurfaceType: [
    { label: "Asphalt", value: "ASPHALT" },
    { label: "Concrete", value: "CONCRETE" },
    { label: "Grass", value: "GRASS" },
    { label: "Gravel", value: "GRAVEL" },
    { label: "Dirt", value: "DIRT" },
    { label: "Composite Materials", value: "COMP_MATERIAL" },
  ],
  GroundVehicleAvailability: [
    { label: "Available", value: "AVAILABLE" },
    { label: "In-Use", value: "IN_USE" },
    { label: "Under-Maintenance", value: "UNDER_MAINTENANCE" },
    { label: "Out-Of-Service", value: "OUT_OF_SERVICE" },
  ],
  GroundVehicleType: [
    { label: "Tug", value: "TUG" },
    { label: "Refueler", value: "REFUELER" },
    { label: "Loader", value: "LOADER" },
    { label: "Catering", value: "CATERING" },
    { label: "De-Icer", value: "DE_ICER" },
    { label: "Pushback", value: "PUSHBACK" },
    { label: "Bus", value: "BUS" },
  ],
};
export default labelValueArrays;
