import GlobalTypes from "@/types/globals";

const selectItems = {
  asArray: {
    AirportType: [
      { label: "International", value: "INTERNATIONAL" },
      { label: "Regional", value: "REGIONAL" },
      { label: "Domestic", value: "DOMESTIC" },
    ],
    CertificationIssuer: [
      { label: "Federal Aviation Administration of United States", value: "FAA" },
      { label: "European Union Aviation Safety Agency", value: "EASA" },
      { label: "Civil Aviation Authority of United Kingdom", value: "CAA_UK" },
      { label: "Civil Aviation Authority of New Zealand", value: "CAA_NZ" },
      { label: "Pakistan Civil Aviation Authority", value: "CAA_PK" },
      { label: "Civil Aviation Department of Hong Kong", value: "CAD_HK" },
      { label: "Civil Aviation Authority of the Philippines", value: "CAA_PH" },
      { label: "Civil Aviation Authority of Singapore", value: "CAA_SG" },
      { label: "Transport Canada", value: "TRANSPORT_CANADA" },
      { label: "Directorate General of Civil Aviation of Turkey", value: "DGCA_TR" },
      { label: "Directorate General of Civil Aviation of India", value: "DGCA_IN" },
      { label: "Directorate General of Civil Aviation of Indonesia", value: "DGCA_ID" },
      { label: "Directorate General of Civil Aviation of Kuwait", value: "DGCA_KW" },
      { label: "Civil Aviation Administration of China", value: "CAAC" },
      { label: "Civil Aviation Safety Authority of Australia", value: "CASA" },
      { label: "International Civil Aviation Organization", value: "ICAO" },
      { label: "National Civil Aviation Agency of Brazil", value: "ANAC" },
      { label: "General Civil Aviation Authority of United Arab Emirates", value: "GCAA" },
      { label: "South African Civil Aviation Authority", value: "SACAA" },
      { label: "International Air Transport Association", value: "IATA" },
      { label: "FlightSafety International", value: "FLIGHT_SAFETY" },
      { label: "Aviation Training & Research Academy", value: "ATRA" },
      { label: "Lufthansa Aviation Training", value: "LAT" },
      { label: "CAE Inc.", value: "CAE" },
    ],
    CrewAvailability: [
      { label: "Available", value: "AVAILABLE" },
      { label: "On-Duty", value: "ON_DUTY" },
      { label: "On-Leave", value: "ON_LEAVE" },
      { label: "Unavailable", value: "UNAVAILABLE" },
    ],
    CrewRole: [
      { label: "Captain", value: "CAPTAIN" },
      { label: "First Officer", value: "FIRST_OFFICER" },
      { label: "Seconds Officer", value: "SECOND_OFFICER" },
      { label: "Third Officer", value: "THIRD_OFFICER" },
      { label: "Relief Crew Member", value: "RELIEF_CREW_MEMBER" },
      { label: "Flight Engineer", value: "FLIGHT_ENGINEER" },
      { label: "Airborne Sensor Opr.", value: "AIRBORNE_SENSOR_OPR" },
      { label: "Purser", value: "PURSER" },
      { label: "Flight Attendant", value: "FLIGHT_ATTENDANT" },
      { label: "Flight Medic", value: "FLIGHT_MEDIC" },
      { label: "Loadmaster", value: "LOADMASTER" },
    ],
    PlaneAvailability: [
      { label: "Available", value: "AVAILABLE" },
      { label: "Under-Maintenance", value: "UNDER_MAINTENANCE" },
      { label: "In-Use", value: "IN_USE" },
      { label: "Retired", value: "RETIRED" },
    ],
    RunwaySurfaceType: [
      { label: "Asphalt", value: "ASPHALT" },
      { label: "Concrete", value: "CONCRETE" },
      { label: "Grass", value: "GRASS" },
      { label: "Gravel", value: "GRAVEL" },
      { label: "Dirt", value: "DIRT" },
      { label: "Composite Materials", value: "COMP_MATERIAL" },
    ],
    GroundVehicleAvailability: [
      { label: "Available", value: "AVAILABLE" },
      { label: "In-Use", value: "IN_USE" },
      { label: "Under-Maintenance", value: "UNDER_MAINTENANCE" },
      { label: "Out-Of-Service", value: "OUT_OF_SERVICE" },
    ],
    GroundVehicleType: [
      { label: "Tug", value: "TUG" },
      { label: "Refueler", value: "REFUELER" },
      { label: "Loader", value: "LOADER" },
      { label: "Catering", value: "CATERING" },
      { label: "De-Icer", value: "DE_ICER" },
      { label: "Pushback", value: "PUSHBACK" },
      { label: "Bus", value: "BUS" },
    ],
    CountryCodes: [
      { label: "United States", value: "US" },
      { label: "Afghanistan", value: "AF" },
      { label: "Aland Islands", value: "AX" },
      { label: "Albania", value: "AL" },
      { label: "Algeria", value: "DZ" },
      { label: "American Samoa", value: "AS" },
      { label: "Andorra", value: "AD" },
      { label: "Angola", value: "AO" },
      { label: "Anguilla", value: "AI" },
      { label: "Antarctica", value: "AQ" },
      { label: "Antigua And Barbuda", value: "AG" },
      { label: "Argentina", value: "AR" },
      { label: "Armenia", value: "AM" },
      { label: "Aruba", value: "AW" },
      { label: "Australia", value: "AU" },
      { label: "Austria", value: "AT" },
      { label: "Azerbaijan", value: "AZ" },
      { label: "Bahamas", value: "BS" },
      { label: "Bahrain", value: "BH" },
      { label: "Bangladesh", value: "BD" },
      { label: "Barbados", value: "BB" },
      { label: "Belarus", value: "BY" },
      { label: "Belgium", value: "BE" },
      { label: "Belize", value: "BZ" },
      { label: "Benin", value: "BJ" },
      { label: "Bermuda", value: "BM" },
      { label: "Bhutan", value: "BT" },
      { label: "Bolivia", value: "BO" },
      { label: "Bonaire, Sint Eustatius, and Saba", value: "BQ" },
      { label: "Bosnia And Herzegovina", value: "BA" },
      { label: "Botswana", value: "BW" },
      { label: "Bouvet Island", value: "BV" },
      { label: "Brazil", value: "BR" },
      { label: "British Indian Ocean Territory", value: "IO" },
      { label: "Brunei Darussalam", value: "BN" },
      { label: "Bulgaria", value: "BG" },
      { label: "Burkina Faso", value: "BF" },
      { label: "Burundi", value: "BI" },
      { label: "Cambodia", value: "KH" },
      { label: "Cameroon", value: "CM" },
      { label: "Canada", value: "CA" },
      { label: "Cape Verde", value: "CV" },
      { label: "Cayman Islands", value: "KY" },
      { label: "Central African Republic", value: "CF" },
      { label: "Chad", value: "TD" },
      { label: "Chile", value: "CL" },
      { label: "China", value: "CN" },
      { label: "Christmas Island", value: "CX" },
      { label: "Cocos (Keeling) Islands", value: "CC" },
      { label: "Colombia", value: "CO" },
      { label: "Comoros", value: "KM" },
      { label: "Congo", value: "CG" },
      { label: "Congo Democratic Republic", value: "CD" },
      { label: "Cook Islands", value: "CK" },
      { label: "Costa Rica", value: "CR" },
      { label: "Cote D'Ivoire", value: "CI" },
      { label: "Croatia", value: "HR" },
      { label: "Cuba", value: "CU" },
      { label: "Curaçao", value: "CW" },
      { label: "Cyprus", value: "CY" },
      { label: "Czech Republic", value: "CZ" },
      { label: "Denmark", value: "DK" },
      { label: "Djibouti", value: "DJ" },
      { label: "Dominica", value: "DM" },
      { label: "Dominican Republic", value: "DO" },
      { label: "Ecuador", value: "EC" },
      { label: "Egypt", value: "EG" },
      { label: "El Salvador", value: "SV" },
      { label: "Equatorial Guinea", value: "GQ" },
      { label: "Eritrea", value: "ER" },
      { label: "Estonia", value: "EE" },
      { label: "Ethiopia", value: "ET" },
      { label: "Falkland Islands", value: "FK" },
      { label: "Faroe Islands", value: "FO" },
      { label: "Fiji", value: "FJ" },
      { label: "Finland", value: "FI" },
      { label: "France", value: "FR" },
      { label: "French Guiana", value: "GF" },
      { label: "French Polynesia", value: "PF" },
      { label: "French Southern Territories", value: "TF" },
      { label: "Gabon", value: "GA" },
      { label: "Gambia", value: "GM" },
      { label: "Georgia", value: "GE" },
      { label: "Germany", value: "DE" },
      { label: "Ghana", value: "GH" },
      { label: "Gibraltar", value: "GI" },
      { label: "Greece", value: "GR" },
      { label: "Greenland", value: "GL" },
      { label: "Grenada", value: "GD" },
      { label: "Guadeloupe", value: "GP" },
      { label: "Guam", value: "GU" },
      { label: "Guatemala", value: "GT" },
      { label: "Guernsey", value: "GG" },
      { label: "Guinea", value: "GN" },
      { label: "Guinea Bissau", value: "GW" },
      { label: "Guyana", value: "GY" },
      { label: "Haiti", value: "HT" },
      { label: "Heard Island and Mcdonald Islands", value: "HM" },
      { label: "Vatican City State", value: "VA" },
      { label: "Honduras", value: "HN" },
      { label: "Hong Kong", value: "HK" },
      { label: "Hungary", value: "HU" },
      { label: "Iceland", value: "IS" },
      { label: "India", value: "IN" },
      { label: "Indonesia", value: "ID" },
      { label: "Iran", value: "IR" },
      { label: "Iraq", value: "IQ" },
      { label: "Ireland", value: "IE" },
      { label: "Isle Of Man", value: "IM" },
      { label: "Israel", value: "IL" },
      { label: "Italy", value: "IT" },
      { label: "Jamaica", value: "JM" },
      { label: "Japan", value: "JP" },
      { label: "Jersey", value: "JE" },
      { label: "Jordan", value: "JO" },
      { label: "Kazakhstan", value: "KZ" },
      { label: "Kenya", value: "KE" },
      { label: "Kiribati", value: "KI" },
      { label: "Republic of Korea", value: "KR" },
      { label: "Democratic People's Republic of Korea", value: "KP" },
      { label: "Kuwait", value: "KW" },
      { label: "Kyrgyzstan", value: "KG" },
      { label: "Lao People'ss Democratic Republic", value: "LA" },
      { label: "Latvia", value: "LV" },
      { label: "Lebanon", value: "LB" },
      { label: "Lesotho", value: "LS" },
      { label: "Liberia", value: "LR" },
      { label: "Libya", value: "LY" },
      { label: "Liechtenstein", value: "LI" },
      { label: "Lithuania", value: "LT" },
      { label: "Luxembourg", value: "LU" },
      { label: "Macao", value: "MO" },
      { label: "Macedonia", value: "MK" },
      { label: "Madagascar", value: "MG" },
      { label: "Malawi", value: "MW" },
      { label: "Malaysia", value: "MY" },
      { label: "Maldives", value: "MV" },
      { label: "Mali", value: "ML" },
      { label: "Malta", value: "MT" },
      { label: "Marshall Islands", value: "MH" },
      { label: "Martinique", value: "MQ" },
      { label: "Mauritania", value: "MR" },
      { label: "Mauritius", value: "MU" },
      { label: "Mayotte", value: "YT" },
      { label: "Mexico", value: "MX" },
      { label: "Micronesia", value: "FM" },
      { label: "Moldova", value: "MD" },
      { label: "Monaco", value: "MC" },
      { label: "Mongolia", value: "MN" },
      { label: "Montenegro", value: "ME" },
      { label: "Montserrat", value: "MS" },
      { label: "Morocco", value: "MA" },
      { label: "Mozambique", value: "MZ" },
      { label: "Myanmar", value: "MM" },
      { label: "Namibia", value: "NA" },
      { label: "Nauru", value: "NR" },
      { label: "Nepal", value: "NP" },
      { label: "Netherlands", value: "NL" },
      { label: "New Caledonia", value: "NC" },
      { label: "New Zealand", value: "NZ" },
      { label: "Nicaragua", value: "NI" },
      { label: "Niger", value: "NE" },
      { label: "Nigeria", value: "NG" },
      { label: "Niue", value: "NU" },
      { label: "Norfolk Island", value: "NF" },
      { label: "Northern Mariana Islands", value: "MP" },
      { label: "Norway", value: "NO" },
      { label: "Oman", value: "OM" },
      { label: "Pakistan", value: "PK" },
      { label: "Palau", value: "PW" },
      { label: "Palestinian Territory", value: "PS" },
      { label: "Panama", value: "PA" },
      { label: "Papua New Guinea", value: "PG" },
      { label: "Paraguay", value: "PY" },
      { label: "Peru", value: "PE" },
      { label: "Philippines", value: "PH" },
      { label: "Pitcairn", value: "PN" },
      { label: "Poland", value: "PL" },
      { label: "Portugal", value: "PT" },
      { label: "PuertoRico", value: "PR" },
      { label: "Qatar", value: "QA" },
      { label: "Reunion", value: "RE" },
      { label: "Romania", value: "RO" },
      { label: "Russian Federation", value: "RU" },
      { label: "Rwanda", value: "RW" },
      { label: "Saint Barthelemy", value: "BL" },
      { label: "Saint Helena", value: "SH" },
      { label: "Saint Kitts And Nevis", value: "KN" },
      { label: "SaintLucia", value: "LC" },
      { label: "SaintMartin", value: "MF" },
      { label: "Saint Pierre And Miquelon", value: "PM" },
      { label: "Saint Vincent And the Grenadines", value: "VC" },
      { label: "Samoa", value: "WS" },
      { label: "San Marino", value: "SM" },
      { label: "Sao Tome And Principe", value: "ST" },
      { label: "Saudi Arabia", value: "SA" },
      { label: "Senegal", value: "SN" },
      { label: "Serbia", value: "RS" },
      { label: "Seychelles", value: "SC" },
      { label: "Sierra Leone", value: "SL" },
      { label: "Singapore", value: "SG" },
      { label: "Sint Maarten", value: "SX" },
      { label: "Slovakia", value: "SK" },
      { label: "Slovenia", value: "SI" },
      { label: "Solomon Islands", value: "SB" },
      { label: "Somalia", value: "SO" },
      { label: "South Africa", value: "ZA" },
      { label: "South Georgia and the South Sandwich Islands", value: "GS" },
      { label: "South Sudan", value: "SS" },
      { label: "Spain", value: "ES" },
      { label: "Sri Lanka", value: "LK" },
      { label: "Sudan", value: "SD" },
      { label: "Suriname", value: "SR" },
      { label: "Svalbard And Jan Mayen", value: "SJ" },
      { label: "Swaziland", value: "SZ" },
      { label: "Sweden", value: "SE" },
      { label: "Switzerland", value: "CH" },
      { label: "Syrian Arab Republic", value: "SY" },
      { label: "Taiwan", value: "TW" },
      { label: "Tajikistan", value: "TJ" },
      { label: "Tanzania", value: "TZ" },
      { label: "Thailand", value: "TH" },
      { label: "Timor Leste", value: "TL" },
      { label: "Togo", value: "TG" },
      { label: "Tokelau", value: "TK" },
      { label: "Tonga", value: "TO" },
      { label: "Trinidad And Tobago", value: "TT" },
      { label: "Tunisia", value: "TN" },
      { label: "Turkey", value: "TR" },
      { label: "Turkmenistan", value: "TM" },
      { label: "Turks And Caicos Islands", value: "TC" },
      { label: "Tuvalu", value: "TV" },
      { label: "Uganda", value: "UG" },
      { label: "Ukraine", value: "UA" },
      { label: "United Arab Emirates", value: "AE" },
      { label: "United Kingdom", value: "GB" },
      { label: "United States Outlying Islands", value: "UM" },
      { label: "Uruguay", value: "UY" },
      { label: "Uzbekistan", value: "UZ" },
      { label: "Vanuatu", value: "VU" },
      { label: "Venezuela", value: "VE" },
      { label: "VietNam", value: "VN" },
      { label: "British Virgin Islands", value: "VG" },
      { label: "US Virgin Islands", value: "VI" },
      { label: "Wallis And Futuna", value: "WF" },
      { label: "Western Sahara", value: "EH" },
      { label: "Yemen", value: "YE" },
      { label: "Zambia", value: "ZM" },
      { label: "Zimbabwe", value: "ZW" },
    ],
  },
  asObject: {
    AirportType: {
      INTERNATIONAL: { label: "International", value: "INTERNATIONAL" },
      REGIONAL: { label: "Regional", value: "REGIONAL" },
      DOMESTIC: { label: "Domestic", value: "DOMESTIC" },
    },
    CertificationIssuer: {
      FAA: { label: "Federal Aviation Administration of United States", value: "FAA" },
      EASA: { label: "European Union Aviation Safety Agency", value: "EASA" },
      CAA_UK: { label: "Civil Aviation Authority of United Kingdom", value: "CAA_UK" },
      CAA_NZ: { label: "Civil Aviation Authority of New Zealand", value: "CAA_NZ" },
      CAA_PK: { label: "Pakistan Civil Aviation Authority", value: "CAA_PK" },
      CAD_HK: { label: "Civil Aviation Department of Hong Kong", value: "CAD_HK" },
      CAA_PH: { label: "Civil Aviation Authority of the Philippines", value: "CAA_PH" },
      CAA_SG: { label: "Civil Aviation Authority of Singapore", value: "CAA_SG" },
      TRANSPORT_CANADA: { label: "Transport Canada", value: "TRANSPORT_CANADA" },
      DGCA_TR: { label: "Directorate General of Civil Aviation of Turkey", value: "DGCA_TR" },
      DGCA_IN: { label: "Directorate General of Civil Aviation of India", value: "DGCA_IN" },
      DGCA_ID: { label: "Directorate General of Civil Aviation of Indonesia", value: "DGCA_ID" },
      DGCA_KW: { label: "Directorate General of Civil Aviation of Kuwait", value: "DGCA_KW" },
      CAAC: { label: "Civil Aviation Administration of China", value: "CAAC" },
      CASA: { label: "Civil Aviation Safety Authority of Australia", value: "CASA" },
      ICAO: { label: "International Civil Aviation Organization", value: "ICAO" },
      ANAC: { label: "National Civil Aviation Agency of Brazil", value: "ANAC" },
      GCAA: { label: "General Civil Aviation Authority of United Arab Emirates", value: "GCAA" },
      SACAA: { label: "South African Civil Aviation Authority", value: "SACAA" },
      IATA: { label: "International Air Transport Association", value: "IATA" },
      FLIGHT_SAFETY: { label: "FlightSafety International", value: "FLIGHT_SAFETY" },
      ATRA: { label: "Aviation Training & Research Academy", value: "ATRA" },
      LAT: { label: "Lufthansa Aviation Training", value: "LAT" },
      CAE: { label: "CAE Inc.", value: "CAE" },
    },
    CrewAvailability: {
      AVAILABLE: { label: "Available", value: "AVAILABLE" },
      ON_DUTY: { label: "On-Duty", value: "ON_DUTY" },
      ON_LEAVE: { label: "On-Leave", value: "ON_LEAVE" },
      UNAVAILABLE: { label: "Unavailable", value: "UNAVAILABLE" },
    },
    CrewRole: {
      CAPTAIN: { label: "Captain", value: "CAPTAIN" },
      FIRST_OFFICER: { label: "First Officer", value: "FIRST_OFFICER" },
      SECOND_OFFICER: { label: "Seconds Officer", value: "SECOND_OFFICER" },
      THIRD_OFFICER: { label: "Third Officer", value: "THIRD_OFFICER" },
      RELIEF_CREW_MEMBER: { label: "Relief Crew Member", value: "RELIEF_CREW_MEMBER" },
      FLIGHT_ENGINEER: { label: "Flight Engineer", value: "FLIGHT_ENGINEER" },
      AIRBORNE_SENSOR_OPR: { label: "Airborne Sensor Opr.", value: "AIRBORNE_SENSOR_OPR" },
      PURSER: { label: "Purser", value: "PURSER" },
      FLIGHT_ATTENDANT: { label: "Flight Attendant", value: "FLIGHT_ATTENDANT" },
      FLIGHT_MEDIC: { label: "Flight Medic", value: "FLIGHT_MEDIC" },
      LOADMASTER: { label: "Loadmaster", value: "LOADMASTER" },
    },
    PlaneAvailability: {
      AVAILABLE: { label: "Available", value: "AVAILABLE" },
      UNDER_MAINTENANCE: { label: "Under-Maintenance", value: "UNDER_MAINTENANCE" },
      IN_USE: { label: "In-Use", value: "IN_USE" },
      RETIRED: { label: "Retired", value: "RETIRED" },
    },
    RunwaySurfaceType: {
      ASPHALT: { label: "Asphalt", value: "ASPHALT" },
      CONCRETE: { label: "Concrete", value: "CONCRETE" },
      GRASS: { label: "Grass", value: "GRASS" },
      GRAVEL: { label: "Gravel", value: "GRAVEL" },
      DIRT: { label: "Dirt", value: "DIRT" },
      COMP_MATERIAL: { label: "Composite Materials", value: "COMP_MATERIAL" },
    },
    GroundVehicleAvailability: {
      AVAILABLE: { label: "Available", value: "AVAILABLE" },
      IN_USE: { label: "In-Use", value: "IN_USE" },
      UNDER_MAINTENANCE: { label: "Under-Maintenance", value: "UNDER_MAINTENANCE" },
      OUT_OF_SERVICE: { label: "Out-Of-Service", value: "OUT_OF_SERVICE" },
    },
    GroundVehicleType: {
      TUG: { label: "Tug", value: "TUG" },
      REFUELER: { label: "Refueler", value: "REFUELER" },
      LOADER: { label: "Loader", value: "LOADER" },
      CATERING: { label: "Catering", value: "CATERING" },
      DE_ICER: { label: "De-Icer", value: "DE_ICER" },
      PUSHBACK: { label: "Pushback", value: "PUSHBACK" },
      BUS: { label: "Bus", value: "BUS" },
    },
    CountryCodes: {
      US: { label: "United States", value: "US" },
      AF: { label: "Afghanistan", value: "AF" },
      AX: { label: "Aland Islands", value: "AX" },
      AL: { label: "Albania", value: "AL" },
      DZ: { label: "Algeria", value: "DZ" },
      AS: { label: "American Samoa", value: "AS" },
      AD: { label: "Andorra", value: "AD" },
      AO: { label: "Angola", value: "AO" },
      AI: { label: "Anguilla", value: "AI" },
      AQ: { label: "Antarctica", value: "AQ" },
      AG: { label: "Antigua And Barbuda", value: "AG" },
      AR: { label: "Argentina", value: "AR" },
      AM: { label: "Armenia", value: "AM" },
      AW: { label: "Aruba", value: "AW" },
      AU: { label: "Australia", value: "AU" },
      AT: { label: "Austria", value: "AT" },
      AZ: { label: "Azerbaijan", value: "AZ" },
      BS: { label: "Bahamas", value: "BS" },
      BH: { label: "Bahrain", value: "BH" },
      BD: { label: "Bangladesh", value: "BD" },
      BB: { label: "Barbados", value: "BB" },
      BY: { label: "Belarus", value: "BY" },
      BE: { label: "Belgium", value: "BE" },
      BZ: { label: "Belize", value: "BZ" },
      BJ: { label: "Benin", value: "BJ" },
      BM: { label: "Bermuda", value: "BM" },
      BT: { label: "Bhutan", value: "BT" },
      BO: { label: "Bolivia", value: "BO" },
      BQ: { label: "Bonaire, Sint Eustatius, and Saba", value: "BQ" },
      BA: { label: "Bosnia And Herzegovina", value: "BA" },
      BW: { label: "Botswana", value: "BW" },
      BV: { label: "Bouvet Island", value: "BV" },
      BR: { label: "Brazil", value: "BR" },
      IO: { label: "British Indian Ocean Territory", value: "IO" },
      BN: { label: "Brunei Darussalam", value: "BN" },
      BG: { label: "Bulgaria", value: "BG" },
      BF: { label: "Burkina Faso", value: "BF" },
      BI: { label: "Burundi", value: "BI" },
      KH: { label: "Cambodia", value: "KH" },
      CM: { label: "Cameroon", value: "CM" },
      CA: { label: "Canada", value: "CA" },
      CV: { label: "Cape Verde", value: "CV" },
      KY: { label: "Cayman Islands", value: "KY" },
      CF: { label: "Central African Republic", value: "CF" },
      TD: { label: "Chad", value: "TD" },
      CL: { label: "Chile", value: "CL" },
      CN: { label: "China", value: "CN" },
      CX: { label: "Christmas Island", value: "CX" },
      CC: { label: "Cocos (Keeling) Islands", value: "CC" },
      CO: { label: "Colombia", value: "CO" },
      KM: { label: "Comoros", value: "KM" },
      CG: { label: "Congo", value: "CG" },
      CD: { label: "Congo Democratic Republic", value: "CD" },
      CK: { label: "Cook Islands", value: "CK" },
      CR: { label: "Costa Rica", value: "CR" },
      CI: { label: "Cote D'Ivoire", value: "CI" },
      HR: { label: "Croatia", value: "HR" },
      CU: { label: "Cuba", value: "CU" },
      CW: { label: "Curaçao", value: "CW" },
      CY: { label: "Cyprus", value: "CY" },
      CZ: { label: "Czech Republic", value: "CZ" },
      DK: { label: "Denmark", value: "DK" },
      DJ: { label: "Djibouti", value: "DJ" },
      DM: { label: "Dominica", value: "DM" },
      DO: { label: "Dominican Republic", value: "DO" },
      EC: { label: "Ecuador", value: "EC" },
      EG: { label: "Egypt", value: "EG" },
      SV: { label: "El Salvador", value: "SV" },
      GQ: { label: "Equatorial Guinea", value: "GQ" },
      ER: { label: "Eritrea", value: "ER" },
      EE: { label: "Estonia", value: "EE" },
      ET: { label: "Ethiopia", value: "ET" },
      FK: { label: "Falkland Islands", value: "FK" },
      FO: { label: "Faroe Islands", value: "FO" },
      FJ: { label: "Fiji", value: "FJ" },
      FI: { label: "Finland", value: "FI" },
      FR: { label: "France", value: "FR" },
      GF: { label: "French Guiana", value: "GF" },
      PF: { label: "French Polynesia", value: "PF" },
      TF: { label: "French Southern Territories", value: "TF" },
      GA: { label: "Gabon", value: "GA" },
      GM: { label: "Gambia", value: "GM" },
      GE: { label: "Georgia", value: "GE" },
      DE: { label: "Germany", value: "DE" },
      GH: { label: "Ghana", value: "GH" },
      GI: { label: "Gibraltar", value: "GI" },
      GR: { label: "Greece", value: "GR" },
      GL: { label: "Greenland", value: "GL" },
      GD: { label: "Grenada", value: "GD" },
      GP: { label: "Guadeloupe", value: "GP" },
      GU: { label: "Guam", value: "GU" },
      GT: { label: "Guatemala", value: "GT" },
      GG: { label: "Guernsey", value: "GG" },
      GN: { label: "Guinea", value: "GN" },
      GW: { label: "Guinea Bissau", value: "GW" },
      GY: { label: "Guyana", value: "GY" },
      HT: { label: "Haiti", value: "HT" },
      HM: { label: "Heard Island and Mcdonald Islands", value: "HM" },
      VA: { label: "Vatican City State", value: "VA" },
      HN: { label: "Honduras", value: "HN" },
      HK: { label: "Hong Kong", value: "HK" },
      HU: { label: "Hungary", value: "HU" },
      IS: { label: "Iceland", value: "IS" },
      IN: { label: "India", value: "IN" },
      ID: { label: "Indonesia", value: "ID" },
      IR: { label: "Iran", value: "IR" },
      IQ: { label: "Iraq", value: "IQ" },
      IE: { label: "Ireland", value: "IE" },
      IM: { label: "Isle Of Man", value: "IM" },
      IL: { label: "Israel", value: "IL" },
      IT: { label: "Italy", value: "IT" },
      JM: { label: "Jamaica", value: "JM" },
      JP: { label: "Japan", value: "JP" },
      JE: { label: "Jersey", value: "JE" },
      JO: { label: "Jordan", value: "JO" },
      KZ: { label: "Kazakhstan", value: "KZ" },
      KE: { label: "Kenya", value: "KE" },
      KI: { label: "Kiribati", value: "KI" },
      KR: { label: "Republic of Korea", value: "KR" },
      KP: { label: "Democratic People's Republic of Korea", value: "KP" },
      KW: { label: "Kuwait", value: "KW" },
      KG: { label: "Kyrgyzstan", value: "KG" },
      LA: { label: "Lao People'ss Democratic Republic", value: "LA" },
      LV: { label: "Latvia", value: "LV" },
      LB: { label: "Lebanon", value: "LB" },
      LS: { label: "Lesotho", value: "LS" },
      LR: { label: "Liberia", value: "LR" },
      LY: { label: "Libya", value: "LY" },
      LI: { label: "Liechtenstein", value: "LI" },
      LT: { label: "Lithuania", value: "LT" },
      LU: { label: "Luxembourg", value: "LU" },
      MO: { label: "Macao", value: "MO" },
      MK: { label: "Macedonia", value: "MK" },
      MG: { label: "Madagascar", value: "MG" },
      MW: { label: "Malawi", value: "MW" },
      MY: { label: "Malaysia", value: "MY" },
      MV: { label: "Maldives", value: "MV" },
      ML: { label: "Mali", value: "ML" },
      MT: { label: "Malta", value: "MT" },
      MH: { label: "Marshall Islands", value: "MH" },
      MQ: { label: "Martinique", value: "MQ" },
      MR: { label: "Mauritania", value: "MR" },
      MU: { label: "Mauritius", value: "MU" },
      YT: { label: "Mayotte", value: "YT" },
      MX: { label: "Mexico", value: "MX" },
      FM: { label: "Micronesia", value: "FM" },
      MD: { label: "Moldova", value: "MD" },
      MC: { label: "Monaco", value: "MC" },
      MN: { label: "Mongolia", value: "MN" },
      ME: { label: "Montenegro", value: "ME" },
      MS: { label: "Montserrat", value: "MS" },
      MA: { label: "Morocco", value: "MA" },
      MZ: { label: "Mozambique", value: "MZ" },
      MM: { label: "Myanmar", value: "MM" },
      NA: { label: "Namibia", value: "NA" },
      NR: { label: "Nauru", value: "NR" },
      NP: { label: "Nepal", value: "NP" },
      NL: { label: "Netherlands", value: "NL" },
      NC: { label: "New Caledonia", value: "NC" },
      NZ: { label: "New Zealand", value: "NZ" },
      NI: { label: "Nicaragua", value: "NI" },
      NE: { label: "Niger", value: "NE" },
      NG: { label: "Nigeria", value: "NG" },
      NU: { label: "Niue", value: "NU" },
      NF: { label: "Norfolk Island", value: "NF" },
      MP: { label: "Northern Mariana Islands", value: "MP" },
      NO: { label: "Norway", value: "NO" },
      OM: { label: "Oman", value: "OM" },
      PK: { label: "Pakistan", value: "PK" },
      PW: { label: "Palau", value: "PW" },
      PS: { label: "Palestinian Territory", value: "PS" },
      PA: { label: "Panama", value: "PA" },
      PG: { label: "Papua New Guinea", value: "PG" },
      PY: { label: "Paraguay", value: "PY" },
      PE: { label: "Peru", value: "PE" },
      PH: { label: "Philippines", value: "PH" },
      PN: { label: "Pitcairn", value: "PN" },
      PL: { label: "Poland", value: "PL" },
      PT: { label: "Portugal", value: "PT" },
      PR: { label: "PuertoRico", value: "PR" },
      QA: { label: "Qatar", value: "QA" },
      RE: { label: "Reunion", value: "RE" },
      RO: { label: "Romania", value: "RO" },
      RU: { label: "Russian Federation", value: "RU" },
      RW: { label: "Rwanda", value: "RW" },
      BL: { label: "Saint Barthelemy", value: "BL" },
      SH: { label: "Saint Helena", value: "SH" },
      KN: { label: "Saint Kitts And Nevis", value: "KN" },
      LC: { label: "SaintLucia", value: "LC" },
      MF: { label: "SaintMartin", value: "MF" },
      PM: { label: "Saint Pierre And Miquelon", value: "PM" },
      VC: { label: "Saint Vincent And the Grenadines", value: "VC" },
      WS: { label: "Samoa", value: "WS" },
      SM: { label: "San Marino", value: "SM" },
      ST: { label: "Sao Tome And Principe", value: "ST" },
      SA: { label: "Saudi Arabia", value: "SA" },
      SN: { label: "Senegal", value: "SN" },
      RS: { label: "Serbia", value: "RS" },
      SC: { label: "Seychelles", value: "SC" },
      SL: { label: "Sierra Leone", value: "SL" },
      SG: { label: "Singapore", value: "SG" },
      SX: { label: "Sint Maarten", value: "SX" },
      SK: { label: "Slovakia", value: "SK" },
      SI: { label: "Slovenia", value: "SI" },
      SB: { label: "Solomon Islands", value: "SB" },
      SO: { label: "Somalia", value: "SO" },
      ZA: { label: "South Africa", value: "ZA" },
      GS: { label: "South Georgia and the South Sandwich Islands", value: "GS" },
      SS: { label: "South Sudan", value: "SS" },
      ES: { label: "Spain", value: "ES" },
      LK: { label: "Sri Lanka", value: "LK" },
      SD: { label: "Sudan", value: "SD" },
      SR: { label: "Suriname", value: "SR" },
      SJ: { label: "Svalbard And Jan Mayen", value: "SJ" },
      SZ: { label: "Swaziland", value: "SZ" },
      SE: { label: "Sweden", value: "SE" },
      CH: { label: "Switzerland", value: "CH" },
      SY: { label: "Syrian Arab Republic", value: "SY" },
      TW: { label: "Taiwan", value: "TW" },
      TJ: { label: "Tajikistan", value: "TJ" },
      TZ: { label: "Tanzania", value: "TZ" },
      TH: { label: "Thailand", value: "TH" },
      TL: { label: "Timor Leste", value: "TL" },
      TG: { label: "Togo", value: "TG" },
      TK: { label: "Tokelau", value: "TK" },
      TO: { label: "Tonga", value: "TO" },
      TT: { label: "Trinidad And Tobago", value: "TT" },
      TN: { label: "Tunisia", value: "TN" },
      TR: { label: "Turkey", value: "TR" },
      TM: { label: "Turkmenistan", value: "TM" },
      TC: { label: "Turks And Caicos Islands", value: "TC" },
      TV: { label: "Tuvalu", value: "TV" },
      UG: { label: "Uganda", value: "UG" },
      UA: { label: "Ukraine", value: "UA" },
      AE: { label: "United Arab Emirates", value: "AE" },
      GB: { label: "United Kingdom", value: "GB" },
      UM: { label: "United States Outlying Islands", value: "UM" },
      UY: { label: "Uruguay", value: "UY" },
      UZ: { label: "Uzbekistan", value: "UZ" },
      VU: { label: "Vanuatu", value: "VU" },
      VE: { label: "Venezuela", value: "VE" },
      VN: { label: "VietNam", value: "VN" },
      VG: { label: "British Virgin Islands", value: "VG" },
      VI: { label: "US Virgin Islands", value: "VI" },
      WF: { label: "Wallis And Futuna", value: "WF" },
      EH: { label: "Western Sahara", value: "EH" },
      YE: { label: "Yemen", value: "YE" },
      ZM: { label: "Zambia", value: "ZM" },
      ZW: { label: "Zimbabwe", value: "ZW" },
    },
  },
};

function getSelectItem<K extends keyof typeof selectItems.asObject>(
  labelValueSection: K,
  enumValue: keyof (typeof selectItems.asObject)[K],
): GlobalTypes.SelectItemProps {
  return selectItems.asObject[labelValueSection][enumValue] as GlobalTypes.SelectItemProps;
}

function getAllLabelsOf<K extends keyof typeof selectItems.asObject>(labelValueSection: K): [string, ...string[]] {
  const items: string[] = Object.values(selectItems.asObject[labelValueSection]).map((item) => item.label);
  return items.length > 1 ? [items[0], ...items.slice(1)] : [items[0]];
}

function getAllValuesOf<K extends keyof typeof selectItems.asObject>(labelValueSection: K): [string, ...string[]] {
  const items: string[] = Object.keys(selectItems.asObject[labelValueSection]);
  return items.length > 1 ? [items[0], ...items.slice(1)] : [items[0]];
}

export { selectItems, getSelectItem, getAllLabelsOf, getAllValuesOf };
