spring:
  application:
    name: FlightCoordinator Auth Service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_name
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 8082
  api_version: v1
  uris:
    webclient: ""
    dataservice: ""
  keys:
    access_key: ""
    refresh_key: ""
