name: Flight Coordinator Default Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  frontend-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.14"

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run security audit
        run: |
          cd frontend
          npm audit

      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      - name: Lint frontend code
        run: |
          cd frontend
          npm run lint

      - name: Format frontend code
        run: |
          cd frontend
          npm run format

  server-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up java (JDK)
        uses: actions/setup-java@v2
        with:
          distribution:
          java-version: "17"

      - name: Install dependencies
        run: |
          cd server
          ./mvnw clean install

      - name: Run server tests
        run: |
          cd server
          ./mvnw test
